# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-03-14 08:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='cool_skill',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='which_hack',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
