# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-03-15 10:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='attendance',
            field=models.CharField(choices=[('1', 'Few hours'), ('2', 'Half event'), ('3', 'Whole event')], default='1', max_length=2),
        ),
        migrations.AddField(
            model_name='application',
            name='english_level',
            field=models.CharField(choices=[('1', 'Low'), ('2', 'Intermediate low'), ('3', 'Intermediate'), ('4', 'Intermediate high'), ('5', 'High')], default='3', max_length=2),
        ),
        migrations.AddField(
            model_name='application',
            name='sponsor_position',
            field=models.CharField(choices=[('DE', 'Developer'), ('DI', 'Director'), ('R', 'Recruiter'), ('M', 'Mentor')], default='DE', max_length=3),
        ),
    ]
