# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-11-16 14:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_reimb_refactor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='authorized_privacy',
        ),
        migrations.AddField(
            model_name='application',
            name='phone_number',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
