# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-03-15 14:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_auto_20200315_0323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='attendance',
            field=models.CharField(choices=[('1', 'Few hours'), ('2', 'Half event'), ('3', 'Whole event')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='english_level',
            field=models.CharField(choices=[('1', 'Low'), ('2', 'Intermediate low'), ('3', 'Intermediate'), ('4', 'Intermediate high'), ('5', 'High')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='sponsor_position',
            field=models.CharField(choices=[('DE', 'Developer'), ('DI', 'Director'), ('R', 'Recruiter'), ('M', 'Mentor')], max_length=3, null=True),
        ),
    ]
