# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-03-14 16:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_auto_20200314_0112'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='company',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
