# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-11-19 23:16
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0004_empty_resume'),
    ]

    operations = [
        migrations.RenameField(
            model_name='application',
            old_name='scholarship',
            new_name='reimb',
        ),
        migrations.AddField(
            model_name='application',
            name='reimb_amount',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0, 'Negative? Really? Please put a positive value')]),
        ),
        migrations.AlterField(
            model_name='application',
            name='phone_number',
            field=models.CharField(blank=True, max_length=16, null=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format:                                                                   '+#########'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')]),
        ),
    ]
