# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-12-05 18:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0005_reimb_amount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='application',
            old_name='origin_city',
            new_name='origin',
        ),
        migrations.RemoveField(
            model_name='application',
            name='origin_country',
        ),
    ]
