# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-12-13 17:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0006_origin_simplified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='team',
        ),
        migrations.RemoveField(
            model_name='application',
            name='teammates',
        ),
        migrations.AlterField(
            model_name='application',
            name='gender',
            field=models.CharField(choices=[('NA', 'Prefer not to answer'), ('M', 'Male'), ('F', 'Female'), ('NB', 'Non-binary')], default='NA', max_length=20),
        ),
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('P', 'Under review'), ('R', 'Wait listed'), ('I', 'Invited'), ('LR', 'Last reminder'), ('C', 'Confirmed'), ('X', 'Cancelled'), ('A', 'Attended'), ('E', 'Expired')], default='P', max_length=2),
        ),
    ]
