# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-01-26 06:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0007_team_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='graduation_year',
            field=models.IntegerField(choices=[(2017, '2017'), (2018, '2018'), (2019, '2019'), (2020, '2020'), (2021, '2021'), (2022, '2022'), (2023, '2023')], default=2017),
        ),
        migrations.AlterField(
            model_name='application',
            name='tshirt_size',
            field=models.CharField(choices=[('XS', 'XS'), ('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('XXL', 'XXL')], default='M', max_length=3),
        ),
    ]
