# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-11-15 01:54
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_user_is_hardware_admin'),
        ('applications', '0009_default_reimb'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='hardware',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.CreateModel(
            name='DraftApplication',
            fields=[
                ('content', models.CharField(max_length=1000)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
