# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-10-27 16:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0010_auto_20181023_1953'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='else_gender',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='gender',
            field=models.CharField(choices=[('NA', 'Prefer not to answer'), ('M', 'Male'), ('F', 'Female'), ('O', 'Other (please specify)')], default='NA', max_length=20),
        ),
    ]
