# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-10-27 16:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0011_auto_20181027_1825'),
    ]

    operations = [
        migrations.RenameField(
            model_name='application',
            old_name='else_gender',
            new_name='other_gender',
        ),
    ]
