# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-07-15 20:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0011_application_cvs_edition'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='cvs_edition',
        ),
    ]
