# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-07-15 21:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0012_remove_application_cvs_edition'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='cvs_edition',
            field=models.BooleanField(default=False),
        ),
    ]
