# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-10-27 18:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0013_auto_20181027_2015'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='other_race',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
