# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2019-02-18 18:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0014_tshirt_fix'),
        ('applications', '0014_gender_other'),
    ]

    operations = [
    ]
