# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-10-27 23:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.datetime_safe


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0014_application_other_race'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='birth_day',
            field=models.DateField(default=django.utils.datetime_safe.date.today),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='application',
            name='under_age',
            field=models.NullBooleanField(),
        ),
    ]
