# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-10-28 11:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0015_auto_20181028_0149'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='major',
            field=models.CharField(default='Unknown', max_length=300),
            preserve_default=False,
        ),
    ]
