# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2019-06-25 16:25
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('applications', '0016_auto_20190611_1011'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='contacted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dubious_applications', to=settings.AUTH_USER_MODEL),
        ),
    ]
