# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-10-28 12:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0016_application_major'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='spirit_animal',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
