# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-07-07 19:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0011_application_cvs_edition'),
        ('applications', '0017_application_contacted_by'),
    ]

    operations = [
    ]
