# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-07-08 10:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0018_merge_20190707_2102'),
        ('applications', '0018_merge_20190705_1210'),
    ]

    operations = [
    ]
