# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-07-08 10:02
from __future__ import unicode_literals

from django.db import migrations, models

import applications


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0018_merge_20190707_2102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to='resumes',
                                   validators=[applications.validators.validate_file_extension]),
        ),
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(
                choices=[('P', 'Under review'), ('R', 'Wait listed'), ('I', 'Invited'), ('LR', 'Last reminder'),
                         ('C', 'Confirmed'), ('X', 'Cancelled'), ('A', 'Attended'), ('E', 'Expired'), ('D', 'Dubious'),
                         ('IV', 'Invalid')], default='P', max_length=2),
        ),
    ]
