# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-03-28 16:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0019_auto_20200321_0441'),
        ('applications', '0019_auto_20200321_1814'),
    ]

    operations = [
    ]
