# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-04-26 15:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0019_auto_20200321_1814'),
        ('applications', '0019_auto_20200210_0838'),
    ]

    operations = [
    ]
