# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-10-28 17:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0019_auto_20181028_1835'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='ambassador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='applications.Ambassador'),
        ),
    ]
