# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-02-06 17:11
from __future__ import unicode_literals

import applications.validatiors
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0019_auto_20200206_0152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to='resumes', validators=[applications.validatiors.validate_file_extension]),
        ),
    ]
