# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-10-28 17:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0020_application_ambassador'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='under_age',
        ),
    ]
