# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-05-20 21:52
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('applications', '0020_new_applications_20200402_1036'),
        ('checkin', '0002_to_new_applications_20200402_1036'),
        ('organizers', '0002_to_new_applications_20200402_1036'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='contacted_by',
        ),
        migrations.RemoveField(
            model_name='application',
            name='invited_by',
        ),
        migrations.RemoveField(
            model_name='application',
            name='user',
        ),
        migrations.RenameField(
            model_name='mentorapplication',
            old_name='projects',
            new_name='participated',
        ),
        migrations.RemoveField(
            model_name='sponsorapplication',
            name='company',
        ),
        migrations.RemoveField(
            model_name='sponsorapplication',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='sponsorapplication',
            name='invited_by',
        ),
        migrations.RemoveField(
            model_name='sponsorapplication',
            name='other_gender',
        ),
        migrations.RemoveField(
            model_name='sponsorapplication',
            name='under_age',
        ),
        migrations.AddField(
            model_name='hackerapplication',
            name='blacklisted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blacklisted_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='hackerapplication',
            name='reviewed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='mentorapplication',
            name='which_hack',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[(0, 'HackAssistant 2016'), (1, 'HackAssistant 2017'), (2, 'HackAssistant 2018'), (3, 'HackAssistant 2019')], max_length=7, null=True),
        ),
        migrations.AddField(
            model_name='sponsorapplication',
            name='name',
            field=models.CharField(default='Name', max_length=255, verbose_name='Full name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='volunteerapplication',
            name='which_hack',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[(0, 'HackAssistant 2016'), (1, 'HackAssistant 2017'), (2, 'HackAssistant 2018'), (3, 'HackAssistant 2019')], max_length=7, null=True),
        ),
        migrations.AlterField(
            model_name='hackerapplication',
            name='status',
            field=models.CharField(choices=[('P', 'Under review'), ('R', 'Wait listed'), ('I', 'Invited'), ('LR', 'Last reminder'), ('C', 'Confirmed'), ('X', 'Cancelled'), ('A', 'Attended'), ('E', 'Expired'), ('D', 'Dubious'), ('IV', 'Invalid'), ('BL', 'Blacklisted')], default='P', max_length=2),
        ),
        migrations.AlterField(
            model_name='mentorapplication',
            name='attendance',
            field=multiselectfield.db.fields.MultiSelectField(choices=[(0, 'Friday'), (1, 'Saturday'), (2, 'Sunday')], max_length=5),
        ),
        migrations.AlterField(
            model_name='mentorapplication',
            name='company',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='mentorapplication',
            name='degree',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='mentorapplication',
            name='english_level',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=0),
        ),
        migrations.AlterField(
            model_name='mentorapplication',
            name='status',
            field=models.CharField(choices=[('P', 'Under review'), ('R', 'Wait listed'), ('I', 'Invited'), ('LR', 'Last reminder'), ('C', 'Confirmed'), ('X', 'Cancelled'), ('A', 'Attended'), ('E', 'Expired'), ('D', 'Dubious'), ('IV', 'Invalid'), ('BL', 'Blacklisted')], default='P', max_length=2),
        ),
        migrations.AlterField(
            model_name='mentorapplication',
            name='study_work',
            field=models.BooleanField(max_length=300),
        ),
        migrations.AlterField(
            model_name='mentorapplication',
            name='university',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='sponsorapplication',
            name='attendance',
            field=multiselectfield.db.fields.MultiSelectField(choices=[(0, 'Friday'), (1, 'Saturday'), (2, 'Sunday')], max_length=5),
        ),
        migrations.AlterField(
            model_name='sponsorapplication',
            name='phone_number',
            field=models.CharField(blank=True, max_length=16, null=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format:                                                                           '+#########'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')]),
        ),
        migrations.AlterField(
            model_name='sponsorapplication',
            name='status',
            field=models.CharField(choices=[('P', 'Under review'), ('R', 'Wait listed'), ('I', 'Invited'), ('LR', 'Last reminder'), ('C', 'Confirmed'), ('X', 'Cancelled'), ('A', 'Attended'), ('E', 'Expired'), ('D', 'Dubious'), ('IV', 'Invalid'), ('BL', 'Blacklisted')], default='C', max_length=2),
        ),
        migrations.AlterField(
            model_name='sponsorapplication',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sponsorapplication_application', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='sponsorapplication',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='volunteerapplication',
            name='attendance',
            field=multiselectfield.db.fields.MultiSelectField(choices=[(0, 'Friday'), (1, 'Saturday'), (2, 'Sunday')], max_length=5),
        ),
        migrations.AlterField(
            model_name='volunteerapplication',
            name='english_level',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=0),
        ),
        migrations.AlterField(
            model_name='volunteerapplication',
            name='status',
            field=models.CharField(choices=[('P', 'Under review'), ('R', 'Wait listed'), ('I', 'Invited'), ('LR', 'Last reminder'), ('C', 'Confirmed'), ('X', 'Cancelled'), ('A', 'Attended'), ('E', 'Expired'), ('D', 'Dubious'), ('IV', 'Invalid'), ('BL', 'Blacklisted')], default='P', max_length=2),
        ),
        migrations.DeleteModel(
            name='Application',
        ),
    ]
