# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-07-08 17:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0020_auto_20190708_1203'),
        ('applications', '0013_application_cvs_edition'),
    ]

    operations = [
    ]
