# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-10-31 20:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0021_remove_application_under_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='job_interest',
            field=models.CharField(choices=[('No', 'Not looking for'), ('Maybe', 'Open'), ('Yes', 'Actively looking for')], default='Maybe', max_length=100),
        ),
        migrations.AddField(
            model_name='application',
            name='job_type',
            field=models.CharField(blank=True, choices=[('internship', 'Internship'), ('part_time', 'Part-time job'), ('full_time', 'Full-time job')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='ambassador',
            name='secret_code',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
