# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-02-23 18:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0021_application_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='type',
        ),
    ]
