# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-04-02 12:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0021_new_application_types_20200402_0508'),
        ('checkin', '0002_to_new_application_20200402_0508'),
        ('organizers', '0002_to_new_application_20200402_0508'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='contacted_by',
        ),
        migrations.RemoveField(
            model_name='application',
            name='invited_by',
        ),
        migrations.RemoveField(
            model_name='application',
            name='user',
        ),
        migrations.DeleteModel(
            name='Application',
        ),
    ]
