# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-04-03 20:42
from __future__ import unicode_literals

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0022_delete_old_applications_20200402_1037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentorapplication',
            name='attendance',
            field=multiselectfield.db.fields.MultiSelectField(choices=[(0, 'Friday'), (1, 'Saturday'), (2, 'Sunday')], max_length=5),
        ),
        migrations.AlterField(
            model_name='mentorapplication',
            name='english_level',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4')], default=0),
        ),
        migrations.AlterField(
            model_name='sponsorapplication',
            name='attendance',
            field=multiselectfield.db.fields.MultiSelectField(choices=[(0, 'Friday'), (1, 'Saturday'), (2, 'Sunday')], max_length=5),
        ),
        migrations.AlterField(
            model_name='volunteerapplication',
            name='attendance',
            field=multiselectfield.db.fields.MultiSelectField(choices=[(0, 'Friday'), (1, 'Saturday'), (2, 'Sunday')], max_length=5),
        ),
        migrations.AlterField(
            model_name='volunteerapplication',
            name='english_level',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4')], default=0),
        ),
        migrations.AddField(
            model_name='mentorapplication',
            name='which_hack',
            field=multiselectfield.db.fields.MultiSelectField(
                choices=[(0, 'HackAssistant 2016'), (1, 'HackAssistant 2017'), (2, 'HackAssistant 2018'),
                         (3, 'HackAssistant 2019')], max_length=7, null=True),
        ),
        migrations.AddField(
            model_name='sponsorapplication',
            name='which_hack',
            field=multiselectfield.db.fields.MultiSelectField(
                choices=[(0, 'HackAssistant 2016'), (1, 'HackAssistant 2017'), (2, 'HackAssistant 2018'),
                         (3, 'HackAssistant 2019')], max_length=7, null=True),
        ),
        migrations.AddField(
            model_name='volunteerapplication',
            name='which_hack',
            field=multiselectfield.db.fields.MultiSelectField(
                choices=[(0, 'HackAssistant 2016'), (1, 'HackAssistant 2017'), (2, 'HackAssistant 2018'),
                         (3, 'HackAssistant 2019')], max_length=7, null=True),
        ),
        migrations.AlterField(
            model_name='mentorapplication',
            name='english_level',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=0),
        ),
        migrations.AlterField(
            model_name='volunteerapplication',
            name='english_level',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=0),
        ),
    ]
