# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-02-23 18:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0022_remove_application_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='type',
            field=models.CharField(choices=[('H', 'Hacker'), ('V', 'Volunteer'), ('M', 'Mentor'), ('S', 'Sponsor')], default='H', max_length=2),
        ),
    ]
