# Generated by Django 3.2.7 on 2021-10-02 11:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('applications', '0022_auto_20200521_0418'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hackerapplication',
            name='blacklisted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blacklisted_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='hackerapplication',
            name='contacted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contacted_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='hackerapplication',
            name='invited_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hackerapplication_invited_applications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='mentorapplication',
            name='invited_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mentorapplication_invited_applications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='sponsorapplication',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sponsorapplication_application', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='volunteerapplication',
            name='invited_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='volunteerapplication_invited_applications', to=settings.AUTH_USER_MODEL),
        ),
    ]
