# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-11-07 18:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0022_auto_20181031_2106'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='lennyface',
        ),
    ]
