# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-11-07 21:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0023_remove_application_lennyface'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='hear_about',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
