# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-11-15 18:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0024_application_hear_about'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='comment',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='visas',
            field=models.BooleanField(default=False),
        ),
    ]
