# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-10-13 07:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0025_auto_20191010_1815'),
        ('applications', '0025_auto_20191010_0029'),
    ]

    operations = [
    ]
