# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-11-15 21:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0025_auto_20181115_1940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='job_interest',
            field=models.CharField(choices=[('No', 'Not looking for'), ('Maybe', 'Open'), ('Yes', 'Actively looking for')], default='Yes', max_length=100),
        ),
    ]
