# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-05-19 18:10
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0026_auto_20200428_0253'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sponsorapplication',
            name='company',
        ),
        migrations.RemoveField(
            model_name='sponsorapplication',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='sponsorapplication',
            name='invited_by',
        ),
        migrations.RemoveField(
            model_name='sponsorapplication',
            name='other_gender',
        ),
        migrations.RemoveField(
            model_name='sponsorapplication',
            name='under_age',
        ),
        migrations.AddField(
            model_name='sponsorapplication',
            name='name',
            field=models.CharField(default='hola', max_length=255, verbose_name='Full name'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sponsorapplication',
            name='phone_number',
            field=models.CharField(blank=True, max_length=16, null=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format:                                                                           '+#########'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')]),
        ),
    ]
