# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-11-17 00:07
from __future__ import unicode_literals

import applications.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0026_auto_20181115_2144'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='guardian_birth_day',
            field=models.DateField(blank=True, null=True, verbose_name='Date of birth of Parent/Legal guardian'),
        ),
        migrations.AddField(
            model_name='application',
            name='guardian_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Full name of Parent/Legal guardian'),
        ),
        migrations.AlterField(
            model_name='application',
            name='graduation_year',
            field=models.IntegerField(choices=[(2018, '2018'), (2019, '2019'), (2020, '2020'), (2021, '2021'), (2022, '2022'), (2023, '2023'), (2024, '2024'), (2025, '2025'), (0, 'Not a university student')], default=2018),
        ),
        migrations.AlterField(
            model_name='application',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to=applications.models.user_directory_path),
        ),
    ]
