# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-05-21 11:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0027_new_application_and_blacklist_20200520_1452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteerapplication',
            name='fav_movie',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='volunteerapplication',
            name='friends',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
