# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-11-17 04:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0028_auto_20181117_0201'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='country',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
