# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-07-09 09:27
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0028_auto_20200521_0418'),
    ]

    operations = [
        migrations.AddField(
            model_name='hackerapplication',
            name='cvs_edition',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='hackerapplication',
            name='hardware',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='hackerapplication',
            name='phone_number',
            field=models.CharField(blank=True, max_length=16, null=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format:                                                                   '+#########'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')]),
        ),
        migrations.AlterField(
            model_name='hackerapplication',
            name='tshirt_size',
            field=models.CharField(choices=[('XS', 'Unisex - XS'), ('S', 'Unisex - S'), ('M', 'Unisex - M'), ('L', 'Unisex - L'), ('XL', 'Unisex - XL'), ('XXL', 'Unisex - XXL'), ('XXXL', 'Unisex - XXXL')], default='M', max_length=5),
        ),
        migrations.AlterField(
            model_name='mentorapplication',
            name='phone_number',
            field=models.CharField(blank=True, max_length=16, null=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format:                                                                   '+#########'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')]),
        ),
        migrations.AlterField(
            model_name='mentorapplication',
            name='tshirt_size',
            field=models.CharField(choices=[('XS', 'Unisex - XS'), ('S', 'Unisex - S'), ('M', 'Unisex - M'), ('L', 'Unisex - L'), ('XL', 'Unisex - XL'), ('XXL', 'Unisex - XXL'), ('XXXL', 'Unisex - XXXL')], default='M', max_length=5),
        ),
        migrations.AlterField(
            model_name='sponsorapplication',
            name='tshirt_size',
            field=models.CharField(choices=[('XS', 'Unisex - XS'), ('S', 'Unisex - S'), ('M', 'Unisex - M'), ('L', 'Unisex - L'), ('XL', 'Unisex - XL'), ('XXL', 'Unisex - XXL'), ('XXXL', 'Unisex - XXXL')], default='M', max_length=5),
        ),
        migrations.AlterField(
            model_name='volunteerapplication',
            name='phone_number',
            field=models.CharField(blank=True, max_length=16, null=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format:                                                                   '+#########'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')]),
        ),
        migrations.AlterField(
            model_name='volunteerapplication',
            name='tshirt_size',
            field=models.CharField(choices=[('XS', 'Unisex - XS'), ('S', 'Unisex - S'), ('M', 'Unisex - M'), ('L', 'Unisex - L'), ('XL', 'Unisex - XL'), ('XXL', 'Unisex - XXL'), ('XXXL', 'Unisex - XXXL')], default='M', max_length=5),
        ),
    ]
