# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-05-20 11:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0028_auto_20200520_0335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sponsorapplication',
            name='status',
            field=models.CharField(choices=[('P', 'Under review'), ('R', 'Wait listed'), ('I', 'Invited'), ('LR', 'Last reminder'), ('C', 'Confirmed'), ('X', 'Cancelled'), ('A', 'Attended'), ('E', 'Expired'), ('D', 'Dubious'), ('IV', 'Invalid')], default='C', max_length=2),
        ),
    ]
