# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-11-17 09:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0030_auto_20181117_0945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='gender',
            field=models.CharField(choices=[('NA', 'Prefer not to answer'), ('M', 'Male'), ('F', 'Female')], default='NA', max_length=20),
        ),
    ]
