# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2021-10-24 15:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0032_auto_20210511_2137'),
    ]

    operations = [
        migrations.AddField(
            model_name='hackerapplication',
            name='online',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='mentorapplication',
            name='online',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='volunteerapplication',
            name='online',
            field=models.BooleanField(default=False),
        ),
    ]
