# Generated by Django 3.2.7 on 2021-11-01 14:58

import applications.models
import applications.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0033_auto_20211024_1744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hackerapplication',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to=applications.models.resume_path_hackers, validators=[applications.validators.validate_file_extension]),
        ),
        migrations.AlterField(
            model_name='mentorapplication',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to=applications.models.resume_path_mentors, validators=[applications.validators.validate_file_extension]),
        ),
    ]
