# Generated by Django 3.2.7 on 2021-11-21 12:58

from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0034_auto_20211101_1558'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcceptedResume',
            fields=[
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='applications.hackerapplication')),
                ('accepted', models.BooleanField()),
            ],
        ),
        migrations.RemoveField(
            model_name='volunteerapplication',
            name='online',
        ),
        migrations.AlterField(
            model_name='hackerapplication',
            name='graduation_year',
            field=models.IntegerField(choices=[(2022, '2022'), (2023, '2023'), (2024, '2024'), (2025, '2025'), (2026, '2026'), (2027, '2027')], default=2022),
        ),
        migrations.AlterField(
            model_name='mentorapplication',
            name='graduation_year',
            field=models.IntegerField(choices=[(2022, '2022'), (2023, '2023'), (2024, '2024'), (2025, '2025'), (2026, '2026'), (2027, '2027')], default=2022),
        ),
        migrations.AlterField(
            model_name='mentorapplication',
            name='which_hack',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[(0, 'HackUPC 2016 Fall'), (1, 'HackUPC 2016 Winter'), (2, 'HackUPC 2017 Fall'), (3, 'HackUPC 2017 Winter'), (4, 'HackUPC 2018'), (5, 'HackUPC 2019'), (6, 'HackUPC2021')], max_length=13, null=True),
        ),
        migrations.AlterField(
            model_name='volunteerapplication',
            name='graduation_year',
            field=models.IntegerField(choices=[(2022, '2022'), (2023, '2023'), (2024, '2024'), (2025, '2025'), (2026, '2026'), (2027, '2027')], default=2022),
        ),
        migrations.AlterField(
            model_name='volunteerapplication',
            name='which_hack',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[(0, 'HackUPC 2016 Fall'), (1, 'HackUPC 2016 Winter'), (2, 'HackUPC 2017 Fall'), (3, 'HackUPC 2017 Winter'), (4, 'HackUPC 2018'), (5, 'HackUPC 2019'), (6, 'HackUPC2021')], max_length=13, null=True),
        ),
    ]
