# Generated by Django 3.2.7 on 2021-12-08 14:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0035_auto_20211121_1358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hackerapplication',
            name='reimb_amount',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0, 'Negative? Really? Please put a positive value'), django.core.validators.MaxValueValidator(200.0, 'Not that much')]),
        ),
    ]
