# Generated by Django 3.2.7 on 2022-01-24 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0037_auto_20211212_1141'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteerapplication',
            name='hobbies',
            field=models.CharField(default=' ', max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='volunteerapplication',
            name='night_shifts',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='hackerapplication',
            name='graduation_year',
            field=models.IntegerField(choices=[(2020, '2020'), (2021, '2021'), (2022, '2022'), (2023, '2023'), (2024, '2024'), (2025, '2025'), (2026, '2026'), (2027, '2027')], default=2023),
        ),
        migrations.AlterField(
            model_name='mentorapplication',
            name='graduation_year',
            field=models.IntegerField(choices=[(2020, '2020'), (2021, '2021'), (2022, '2022'), (2023, '2023'), (2024, '2024'), (2025, '2025'), (2026, '2026'), (2027, '2027')], default=2023),
        ),
        migrations.AlterField(
            model_name='volunteerapplication',
            name='graduation_year',
            field=models.IntegerField(choices=[(2020, '2020'), (2021, '2021'), (2022, '2022'), (2023, '2023'), (2024, '2024'), (2025, '2025'), (2026, '2026'), (2027, '2027')], default=2023),
        ),
    ]
