# Generated by Django 3.2.7 on 2022-04-26 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0038_auto_20220124_1003'),
    ]

    operations = [
        migrations.AddField(
            model_name='sponsorapplication',
            name='email',
            field=models.EmailField(max_length=255, null=True, verbose_name='email'),
        ),
    ]
