# Generated by Django 3.2.7 on 2023-02-25 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0039_sponsorapplication_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteerapplication',
            name='volunteer_motivation',
            field=models.CharField(default=' ', max_length=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='hackerapplication',
            name='graduation_year',
            field=models.IntegerField(choices=[(2022, '2022'), (2023, '2023'), (2024, '2024'), (2025, '2025'), (2026, '2026'), (2027, '2027'), (2028, '2028'), (2029, '2029')], default=2024),
        ),
        migrations.AlterField(
            model_name='mentorapplication',
            name='graduation_year',
            field=models.IntegerField(choices=[(2022, '2022'), (2023, '2023'), (2024, '2024'), (2025, '2025'), (2026, '2026'), (2027, '2027'), (2028, '2028'), (2029, '2029')], default=2024),
        ),
        migrations.AlterField(
            model_name='volunteerapplication',
            name='graduation_year',
            field=models.IntegerField(choices=[(2022, '2022'), (2023, '2023'), (2024, '2024'), (2025, '2025'), (2026, '2026'), (2027, '2027'), (2028, '2028'), (2029, '2029')], default=2024),
        ),
        migrations.AlterField(
            model_name='volunteerapplication',
            name='night_shifts',
            field=models.BooleanField(null=True),
        ),
    ]
