# Generated by Django 3.2.7 on 2023-04-02 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0041_auto_20230303_1741'),
    ]

    operations = [
        migrations.AddField(
            model_name='hackerapplication',
            name='mlh_optional_communications',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='hackerapplication',
            name='mlh_required_terms',
            field=models.BooleanField(default=False),
        ),
    ]
