# Generated by Django 3.2.7 on 2024-01-10 11:16

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0041_auto_20230303_1741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hackerapplication',
            name='graduation_year',
            field=models.IntegerField(choices=[(2022, '2022'), (2023, '2023'), (2024, '2024'), (2025, '2025'), (2026, '2026'), (2027, '2027'), (2028, '2028'), (2029, '2029')], default=2025),
        ),
        migrations.AlterField(
            model_name='mentorapplication',
            name='graduation_year',
            field=models.IntegerField(choices=[(2022, '2022'), (2023, '2023'), (2024, '2024'), (2025, '2025'), (2026, '2026'), (2027, '2027'), (2028, '2028'), (2029, '2029')], default=2025),
        ),
        migrations.AlterField(
            model_name='volunteerapplication',
            name='attendance',
            field=multiselectfield.db.fields.MultiSelectField(choices=[(0, 'Viernes'), (1, 'Sábado'), (2, 'Domingo')], max_length=5),
        ),
        migrations.AlterField(
            model_name='volunteerapplication',
            name='diet',
            field=models.CharField(choices=[('None', 'Sin requerimientos'), ('Vegetarian', 'Vegetariano'), ('Vegan', 'Vegano'), ('Gluten-free', 'Sin gluten'), ('Others', 'Otros')], default='None', max_length=300),
        ),
        migrations.AlterField(
            model_name='volunteerapplication',
            name='english_level',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Spanish', 'Español'), ('Catalan', 'Catalán'), ('English', 'Inglés')], max_length=23),
        ),
        migrations.AlterField(
            model_name='volunteerapplication',
            name='gender',
            field=models.CharField(choices=[('NA', 'Prefiero no responder'), ('M', 'Hombre'), ('F', 'Mujer'), ('NB', 'No binario'), ('X', 'Prefiero describirme')], default='NA', max_length=23),
        ),
        migrations.AlterField(
            model_name='volunteerapplication',
            name='graduation_year',
            field=models.IntegerField(choices=[(2022, '2022'), (2023, '2023'), (2024, '2024'), (2025, '2025'), (2026, '2026'), (2027, '2027'), (2028, '2028'), (2029, '2029')], default=2025),
        ),
        migrations.AlterField(
            model_name='volunteerapplication',
            name='which_hack',
            field=multiselectfield.db.fields.MultiSelectField(choices=[(0, 'HackUPC 2016 Fall'), (1, 'HackUPC 2016 Winter'), (2, 'HackUPC 2017 Fall'), (3, 'HackUPC 2017 Winter'), (4, 'HackUPC 2018'), (5, 'HackUPC 2019'), (6, 'HackUPC 2021'), (7, 'HackUPC 2022')], max_length=15),
        ),
    ]
