# Generated by Django 3.2.7 on 2023-12-30 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0041_auto_20230303_1741'),
    ]

    operations = [
        migrations.AddField(
            model_name='hackerapplication',
            name='discover',
            field=models.IntegerField(default=False),
        ),
    ]
