# Generated by Django 3.2.7 on 2023-04-02 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0042_auto_20230402_1844'),
    ]

    operations = [
        migrations.AddField(
            model_name='hackerapplication',
            name='mlh_required_privacy',
            field=models.BooleanField(default=False),
        ),
    ]
