# Generated by Django 3.2.23 on 2024-01-24 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0042_auto_20240119_1908'),
        ('applications', '0042_hackerapplication_discover'),
        ('applications', '0043_auto_20240110_1257'),
    ]

    operations = [
    ]
