# Generated by Django 3.2.7 on 2024-01-10 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0044_hackerapplication_discover'),
    ]

    operations = [
        migrations.RenameField(
            model_name='volunteerapplication',
            old_name='english_level',
            new_name='languages',
        ),
        migrations.AddField(
            model_name='volunteerapplication',
            name='hear_about_us',
            field=models.CharField(default='', max_length=300),
        ),
    ]
