# Generated by Django 3.2.23 on 2024-02-02 08:52

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0045_auto_20240110_1257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hackerapplication',
            name='diet',
            field=models.CharField(choices=[('None', 'No requirements'), ('Vegetarian', 'Vegetarian'), ('Vegan', 'Vegan'), ('Gluten-free', 'Gluten-free'), ('Others', 'Others')], default='None', max_length=300),
        ),
        migrations.AlterField(
            model_name='mentorapplication',
            name='diet',
            field=models.CharField(choices=[('None', 'No requirements'), ('Vegetarian', 'Vegetarian'), ('Vegan', 'Vegan'), ('Gluten-free', 'Gluten-free'), ('Others', 'Others')], default='None', max_length=300),
        ),
        migrations.AlterField(
            model_name='mentorapplication',
            name='which_hack',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[(0, 'HackUPC 2016 Fall'), (1, 'HackUPC 2016 Winter'), (2, 'HackUPC 2017 Fall'), (3, 'HackUPC 2017 Winter'), (4, 'HackUPC 2018'), (5, 'HackUPC 2019'), (6, 'HackUPC 2021'), (7, 'HackUPC 2022'), (8, 'HackUPC 2023')], max_length=17, null=True),
        ),
        migrations.AlterField(
            model_name='sponsorapplication',
            name='diet',
            field=models.CharField(choices=[('None', 'No requirements'), ('Vegetarian', 'Vegetarian'), ('Vegan', 'Vegan'), ('Gluten-free', 'Gluten-free'), ('Others', 'Others')], default='None', max_length=300),
        ),
        migrations.AlterField(
            model_name='volunteerapplication',
            name='hear_about_us',
            field=models.CharField(choices=[('Posters', 'Posters'), ('Redes Sociales', 'Redes Sociales'), ('Mesas en el bar de la FIB', 'Mesas en el bar de la FIB'), ('Whatsapp, amigos u otras personas', 'Whatsapp, amigos u otras personas'), ('Web', 'Web'), ('Otros', 'Otros')], default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='volunteerapplication',
            name='which_hack',
            field=multiselectfield.db.fields.MultiSelectField(choices=[(0, 'HackUPC 2016 Fall'), (1, 'HackUPC 2016 Winter'), (2, 'HackUPC 2017 Fall'), (3, 'HackUPC 2017 Winter'), (4, 'HackUPC 2018'), (5, 'HackUPC 2019'), (6, 'HackUPC 2021'), (7, 'HackUPC 2022'), (8, 'HackUPC 2023')], max_length=17),
        ),
    ]
