# Generated by Django 3.2.23 on 2024-02-04 12:12

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0047_auto_20240202_1020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteerapplication',
            name='night_shifts',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('No', 'No'), ('Yes', 'Sí'), ('Maybe', 'Puede ser')], default='No', max_length=12),
        ),
    ]
