# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-02-14 16:47
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0016_auto_20200709_1127'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscordUser',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('discord_id', models.CharField(max_length=50, unique=True)),
                ('checked_in', models.BooleanField(default=False)),
            ],
        ),
    ]
