# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-02-21 11:59
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscordUser',
            fields=[
                ('discord_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('discord_username', models.CharField(max_length=100, null=True)),
                ('checked_in', models.BooleanField(default=False)),
                ('team_name', models.CharField(max_length=100, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
