# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-03-09 18:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discord', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='discorduser',
            name='address',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='discorduser',
            name='swag',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='discorduser',
            name='team_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
