# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-02-20 13:47
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('discord', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='discorduser',
            name='team_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='discorduser',
            name='discord_id',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='discorduser',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
