# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-02-20 16:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discord', '0002_auto_20210220_1447'),
    ]

    operations = [
        migrations.AddField(
            model_name='discorduser',
            name='discord_username',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
