# Generated by Django 3.2.7 on 2022-04-26 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='kind',
            field=models.CharField(choices=[('B', 'Breakfast'), ('L', 'Lunch'), ('D', 'Dinner'), ('S', 'Snack'), ('O', 'Other'), ('SH', 'Shower'), ('A', 'Activity')], max_length=63),
        ),
    ]
