language: python
python:
  - "2.7"
  - "3.5"
  - "3.5-dev" # 3.5 development branch
  - "3.6"
  - "3.6-dev" # 3.6 development branch
install: "pip install -r requirements.txt"
script:
  - ./manage.py test
  - flake8
