# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-11-15 17:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vote',
            name='culture',
            field=models.IntegerField(choices=[(1, 'Kosice'), (2, 'CZ/SK'), (3, 'Europe'), (4, 'Extreme')], null=True),
        ),
        migrations.AddField(
            model_name='vote',
            name='passion',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], null=True),
        ),
        migrations.AlterField(
            model_name='vote',
            name='personal',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], null=True),
        ),
        migrations.AlterField(
            model_name='vote',
            name='tech',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], null=True),
        ),
    ]
