# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-10-24 06:12
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hackers.Application'),
        ),
        migrations.AlterField(
            model_name='vote',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
