# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-07-09 11:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizers', '0003_application_comment_to_all_applications_20200520_1452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='personal',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], null=True),
        ),
        migrations.AlterField(
            model_name='vote',
            name='tech',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], null=True),
        ),
    ]
