from escpos.printer import Usb
from escpos.escpos import EscposIO
p = Usb(0x0416, 0x5011)
p2 = EscposIO(p)
p.text("\n")
p.image("/home/oriolclosa/Documents/HackUPC/GitHub/registration/baggage/static/img/printer/header.gif")
p.text("\n")
p.text("\n")
p.image("/home/oriolclosa/Documents/HackUPC/GitHub/registration/baggage/static/img/printer/title.gif")
p.text("\n")
p2.writelines("Printed on: 18/09/2018 21:05:36", align='center', font='b')
p.text("\n")
p.text("\n")
p2.writelines("Location", align='center', font='a', text_type='bold', width=1)
p2.writelines("E01-A4", align='center', font='a', text_type='bold', width=2, height=2)
p.text("\n")
p.text("\n")
p2.writelines("Name: Oriol Closa", align='center', font='a', text_type='bold')
p2.writelines("Email: oriol@hackupc.com", align='center', font='a', text_type='bold')
p.text("\n")
p.text("\n")
p2.writelines("Time: 18/09/2018 21:05:36", align='center', font='a')
p.text("\n")
p.text("\n")
p.image("/home/oriolclosa/Documents/HackUPC/GitHub/registration/baggage/static/img/printer/footer.gif")
p.cut()
