# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-09-29 20:03
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Challenge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Presentation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('turn', models.IntegerField(null=True)),
                ('done', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True)),
                ('url', models.URLField(blank=True)),
                ('description', models.CharField(max_length=2000)),
                ('video', models.URLField(blank=True, null=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('file_url', models.URLField(blank=True, null=True)),
                ('desired_prizes', models.CharField(max_length=400)),
                ('built_with', models.CharField(blank=True, max_length=400, null=True)),
                ('submitter_screen_name', models.CharField(blank=True, max_length=200, null=True)),
                ('submitter_first_name', models.CharField(blank=True, max_length=100, null=True)),
                ('submitter_last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('submitter_email', models.CharField(blank=True, max_length=200, null=True)),
                ('university', models.CharField(blank=True, max_length=300, null=True)),
                ('additional_team_member_count', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, unique=True)),
                ('challenge', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='judging.Challenge')),
                ('main_judge', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='presentation',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='judging.Project'),
        ),
        migrations.AddField(
            model_name='presentation',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='judging.Room'),
        ),
        migrations.AlterUniqueTogether(
            name='presentation',
            unique_together=set([('project', 'room')]),
        ),
    ]
