# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-10-16 04:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('judging', '0003_auto_20181012_2229'),
        ('judging', '0003_auto_20181004_2230'),
    ]

    operations = [
    ]
