# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-10-21 08:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judging', '0005_auto_20181021_0958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='built_with',
            field=models.CharField(blank=True, max_length=20000, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='desired_prizes',
            field=models.CharField(max_length=8000),
        ),
        migrations.AlterField(
            model_name='project',
            name='submitter_email',
            field=models.CharField(blank=True, max_length=6000, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='submitter_first_name',
            field=models.CharField(blank=True, max_length=6000, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='submitter_last_name',
            field=models.CharField(blank=True, max_length=6000, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='submitter_screen_name',
            field=models.CharField(blank=True, max_length=6000, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='title',
            field=models.CharField(max_length=2000, unique=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='university',
            field=models.CharField(blank=True, max_length=6000, null=True),
        ),
    ]
