# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-11-08 17:43
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0002_auto_20171101_1602'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reimbursement',
            fields=[
                ('assigned_money', models.FloatField()),
                ('reimbursement_money', models.FloatField(blank=True, null=True)),
                ('public_comment', models.CharField(blank=True, max_length=300, null=True)),
                ('paypal_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('receipt', models.FileField(blank=True, null=True, upload_to=b'')),
                ('multiple_hackers', models.BooleanField(default=False)),
                ('friend_emails', models.CharField(blank=True, max_length=400, null=True)),
                ('origin_city', models.CharField(max_length=300)),
                ('origin_country', models.CharField(max_length=300)),
                ('hacker', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('expiration_time', models.DateTimeField(blank=True, null=True)),
                ('update_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('creation_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('D', 'Pending review'), ('W', 'Wait listed'), ('PT', 'Pending ticket submission'), ('PA', 'Pending ticket approval'), ('A', 'Ticket approved'), ('FS', 'Friend submission')], default='D', max_length=2)),
                ('friend_submission', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='friend_submissions', to='reimbursement.Reimbursement')),
                ('reimbursed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reimbursements_made', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
