# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-06-29 21:35
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('register', '0008_reimbursements'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reimbursement',
            fields=[
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='register.Application')),
                ('assigned_money', models.FloatField(blank=True, null=True)),
                ('origin_city', models.CharField(max_length=300)),
                ('origin_country', models.CharField(max_length=300)),
                ('status', models.CharField(choices=[('P', 'Pending'), ('S', 'Sent')], default='P', max_length=2)),
                ('creation_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('reimbursed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': (('reimburse', 'Can assign reimbursements'),),
            },
        ),
    ]
