# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-06-29 21:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('reimbursement', '0001_reimbursements'),
    ]

    operations = [
        migrations.AddField(
            model_name='reimbursement',
            name='status_update_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
