# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-11-16 05:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reimbursement', '0002_reimbursement_venmo_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reimbursement',
            name='receipt',
            field=models.FileField(blank=True, null=True, upload_to='receipt'),
        ),
        migrations.AlterField(
            model_name='reimbursement',
            name='status',
            field=models.CharField(choices=[('D', 'Pending review'), ('W', 'Wait listed'), ('PT', 'Pending receipt submission'), ('PA', 'Pending receipt approval'), ('A', 'Receipt approved'), ('FS', 'Friend submission')], default='D', max_length=2),
        ),
    ]
