# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-06-29 22:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reimbursement', '0002_status_update'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reimbursement',
            name='status',
            field=models.CharField(choices=[('P', 'Not sent'), ('S', 'Sent')], default='P', max_length=2),
        ),
    ]
