# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-06-29 23:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reimbursement', '0003_not_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='reimbursement',
            name='currency_sign',
            field=models.CharField(default='\u20ac', max_length=3),
        ),
    ]
