# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-01-29 18:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reimbursement', '0004_origin_simplified'),
    ]

    operations = [
        migrations.AddField(
            model_name='reimbursement',
            name='address',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='reimbursement',
            name='status',
            field=models.CharField(choices=[('D', 'Pending review'), ('W', 'Wait listed'), ('PT', 'Pending receipt submission'), ('PA', 'Pending receipt approval'), ('A', 'Receipt approved'), ('X', 'Expired'), ('FS', 'Friend submission')], default='D', max_length=2),
        ),
    ]
