# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-09-01 01:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reimbursement', '0004_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='reimbursement',
            name='reviewer_comment',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='reimbursement',
            name='status',
            field=models.CharField(choices=[('P', 'Draft'), ('S', 'Sent'), ('A', 'Accepted'), ('FA', 'Friend accepted'), ('NC', 'Needs change')], default='P', max_length=2),
        ),
    ]
