# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-11-22 16:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reimbursement', '0005_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='reimbursement',
            name='account_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='reimbursement',
            name='bank',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='reimbursement',
            name='iban',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
