# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-09-01 01:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reimbursement', '0005_reimb_management'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reimbursement',
            old_name='reviewer_comment',
            new_name='change_reason',
        ),
    ]
