# Generated by Django 3.2.7 on 2021-11-21 12:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reimbursement', '0005_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reimbursement',
            name='reimbursed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reimbursements_made', to=settings.AUTH_USER_MODEL),
        ),
    ]
