# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-09-03 23:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reimbursement', '0006_change_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='reimbursement',
            name='paypal_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
