# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-08-08 19:12
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('active', models.BooleanField(default=True)),
                ('type', models.CharField(choices=[('LAPTOP', 'Laptop')], max_length=10)),
                ('color', models.CharField(choices=[('BE', 'Beige'), ('BK', 'Black'), ('BL', 'Blue'), ('BW', 'Brown'), ('CO', 'Coral'), ('CY', 'Cyan'), ('GR', 'Green'), ('GY', 'Grey'), ('LA', 'Lavender'), ('LI', 'Lime'), ('MA', 'Magenta'), ('MO', 'Maroon'), ('MI', 'Mint'), ('NA', 'Navy'), ('OL', 'Olive'), ('OR', 'Orange'), ('PI', 'Pink'), ('PU', 'Purple'), ('RE', 'Red'), ('TE', 'Teal'), ('WH', 'White'), ('YE', 'Yellow')], max_length=2)),
                ('description', models.TextField(blank=True, max_length=1023, null=True)),
                ('special', models.BooleanField(default=False)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Movement',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('time', models.DateField(auto_now_add=True)),
                ('type', models.CharField(max_length=3)),
                ('comment', models.TextField(blank=True, max_length=1023, null=True)),
                ('receipt', models.BooleanField(default=False)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='baggage.Item')),
                ('manager', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('building', models.CharField(max_length=63)),
                ('row', models.CharField(max_length=63)),
                ('column', models.PositiveSmallIntegerField()),
                ('content', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='baggage.Item')),
            ],
        ),
        migrations.AddField(
            model_name='movement',
            name='position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='baggage.Position'),
        ),
        migrations.AlterUniqueTogether(
            name='position',
            unique_together=set([('building', 'row', 'column')]),
        ),
    ]
