# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-09-22 23:35
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bag',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('A', 'Added'), ('R', 'Removed')], default='A', max_length=1)),
                ('row', models.CharField(max_length=15)),
                ('col', models.PositiveIntegerField()),
                ('type', models.CharField(max_length=10)),
                ('color', models.CharField(max_length=2)),
                ('description', models.TextField(blank=True, max_length=1023, null=True)),
                ('special', models.BooleanField(default=False)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('image', models.FileField(blank=True, null=True, upload_to='baggage')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('comment', models.TextField(blank=True, max_length=1023, null=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='baggage.Bag')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('room', models.CharField(choices=[('E01', 'E01'), ('E02', 'E02')], max_length=63, primary_key=True, serialize=False)),
                ('row', models.PositiveIntegerField(default=0)),
                ('col', models.PositiveIntegerField(default=0)),
                ('door_row', models.PositiveIntegerField(default=0)),
                ('door_col', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='bag',
            name='room',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='baggage.Room'),
        ),
    ]
