# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-10-19 13:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baggage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bag',
            name='btype',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='bag',
            name='color',
            field=models.CharField(max_length=255),
        ),
    ]
