# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-09-27 07:58
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('baggage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bag',
            name='inby',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='bag_baggage_in', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bag',
            name='outby',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bag_requests_out', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='bag',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bag_baggage_owner', to=settings.AUTH_USER_MODEL),
        ),
    ]
