# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-08-09 06:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baggage', '0004_bag_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bag',
            name='status',
            field=models.CharField(choices=[('A', 'Added'), ('R', 'Removed')], default='A', max_length=1),
        ),
    ]
