# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-08-09 06:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.datetime_safe


class Migration(migrations.Migration):

    dependencies = [
        ('baggage', '0005_auto_20180809_0810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bag',
            name='time',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='bag',
            name='updated',
            field=models.DateTimeField(auto_now=True, default=django.utils.datetime_safe.datetime.now),
            preserve_default=False,
        ),
    ]
