# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-08-10 07:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('baggage', '0006_auto_20180809_0815'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='position',
            name='content',
        ),
        migrations.AddField(
            model_name='bag',
            name='position',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='baggage.Position'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='position',
            name='occupied',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='position',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
