# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-09-03 16:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baggage', '0009_auto_20180810_0923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='building',
            field=models.CharField(choices=[('E01', 'E01'), ('E02', 'E02')], max_length=63),
        ),
    ]
