# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-09-15 15:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baggage', '0010_auto_20180903_1853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bag',
            name='type',
            field=models.CharField(choices=[('BAC', 'Backpack'), ('HAR', 'Hardware'), ('CLO', 'Clothes'), ('OTH', 'Other')], max_length=10),
        ),
        migrations.AlterField(
            model_name='position',
            name='building',
            field=models.CharField(choices=[('A5E01', 'A5E01'), ('A5E02', 'A5E02')], max_length=63),
        ),
    ]
