# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-09-16 11:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('baggage', '0011_auto_20180915_1722'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('room', models.CharField(choices=[('E01', 'E01'), ('E02', 'E02')], max_length=63, primary_key=True, serialize=False)),
                ('row', models.PositiveIntegerField(default=0)),
                ('col', models.PositiveIntegerField(default=0)),
                ('door_row', models.PositiveIntegerField(default=0)),
                ('door_col', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.DeleteModel(
            name='Position',
        ),
        migrations.AlterField(
            model_name='bag',
            name='position',
            field=models.CharField(max_length=31),
        ),
        migrations.AddField(
            model_name='bag',
            name='room',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='baggage.Room'),
            preserve_default=False,
        ),
    ]
