# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-09-16 11:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baggage', '0012_auto_20180916_1353'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bag',
            name='position',
        ),
        migrations.AddField(
            model_name='bag',
            name='col',
            field=models.PositiveIntegerField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bag',
            name='row',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
