# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-09-16 13:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baggage', '0014_bag_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bag',
            name='row',
            field=models.CharField(max_length=15),
        ),
    ]
