# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-09-22 20:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('baggage', '0015_auto_20180916_1556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bag',
            name='room',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='baggage.Room'),
        ),
    ]
