# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-09-22 20:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baggage', '0016_auto_20180922_2207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bag',
            name='color',
            field=models.CharField(max_length=2),
        ),
        migrations.AlterField(
            model_name='bag',
            name='type',
            field=models.CharField(max_length=10),
        ),
    ]
