# Generated by Django 3.2.7 on 2021-12-08 12:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hardware', '0003_rename_lending_to_borrowing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowing',
            name='borrowing_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='hardware_admin_borrowing', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='borrowing',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='hardware.item'),
        ),
        migrations.AlterField(
            model_name='borrowing',
            name='return_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hardware_admin_return', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='borrowing',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
