# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-10-24 05:23
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('submission_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('status_update_date', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('P', 'Pending'), ('R', 'Rejected'), ('I', 'Invited'), ('LR', 'Last reminder'), ('C', 'Confirmed'), ('X', 'Cancelled'), ('A', 'Attended'), ('E', 'Expired')], default='P', max_length=2)),
                ('gender', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('NB', 'Non-binary')], max_length=20, null=True)),
                ('under_age', models.BooleanField()),
                ('origin_city', models.CharField(max_length=300)),
                ('origin_country', models.CharField(max_length=300)),
                ('first_timer', models.BooleanField()),
                ('description', models.TextField(max_length=500)),
                ('projects', models.TextField(max_length=500)),
                ('scholarship', models.BooleanField()),
                ('lennyface', models.CharField(default='-.-', max_length=300)),
                ('resume', models.FileField(blank=True, null=True, upload_to=b'')),
                ('authorized_privacy', models.BooleanField(default=False)),
                ('graduation_year', models.IntegerField(choices=[(2016, b'2016'), (2017, b'2017'), (2018, b'2018'), (2019, b'2019'), (2020, b'2020'), (2021, b'2021'), (2022, b'2022')])),
                ('university', models.CharField(max_length=300)),
                ('degree', models.CharField(max_length=300)),
                ('github', models.URLField(blank=True, null=True)),
                ('devpost', models.URLField(blank=True, null=True)),
                ('linkedin', models.URLField(blank=True, null=True)),
                ('site', models.URLField(blank=True, null=True)),
                ('diet', models.CharField(choices=[('None', 'No requirements'), ('Vegeterian', 'Vegeterian'), ('Vegan', 'Vegan'), ('No pork', 'No pork'), ('Gluten-free', 'Gluten-free'), ('Others', 'Others')], max_length=300)),
                ('other_diet', models.CharField(blank=True, max_length=600, null=True)),
                ('tshirt_size', models.CharField(choices=[('XS', 'XS'), ('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL')], default='M', max_length=3)),
                ('team', models.BooleanField()),
                ('teammates', models.CharField(blank=True, max_length=300, null=True)),
                ('invited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invited_applications', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
