# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-06-23 19:12
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.TextField(primary_key=True, serialize=False)),
                ('submission_date', models.DateTimeField()),
                ('invitation_date', models.DateTimeField(blank=True, null=True)),
                ('last_reminder', models.DateTimeField(blank=True, null=True)),
                ('sendgrid_id', models.TextField(default='')),
                ('name', models.TextField()),
                ('lastname', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('country', models.TextField()),
                ('under_age', models.NullBooleanField()),
                ('gender', models.TextField(null=True)),
                ('graduationYear', models.IntegerField()),
                ('university', models.TextField()),
                ('degree', models.TextField(default='Computer Science')),
                ('github', models.URLField()),
                ('devpost', models.URLField()),
                ('linkedin', models.URLField()),
                ('site', models.URLField()),
                ('resume', models.URLField()),
                ('first_timer', models.NullBooleanField()),
                ('description', models.TextField()),
                ('projects', models.TextField()),
                ('diet', models.TextField()),
                ('tshirt_size', models.CharField(default='M', max_length=3)),
                ('scholarship', models.NullBooleanField()),
                ('reimbursement_money', models.IntegerField(blank=True, null=True)),
                ('lennyface', models.TextField(default='-.-')),
                ('team', models.NullBooleanField()),
                ('teammates', models.TextField(default='None')),
                ('authorized_mlh', models.NullBooleanField()),
                ('status', models.CharField(choices=[('S', 'Started'), ('P', 'Completed'), ('R', 'Rejected'), ('I', 'Invited'), ('C', 'Confirmed'), ('X', 'Cancelled'), ('T', 'Attended'), ('E', 'Expired')], default='S', max_length=2)),
                ('invited_by', models.TextField(null=True)),
            ],
            options={
                'permissions': (('invite', 'Can invite applications'), ('vote', 'Can review applications'), ('checkin', 'Can check-in applications'), ('reject', 'Can reject applications'), ('ranking', 'Can view voting ranking')),
            },
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tech', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10')], null=True)),
                ('personal', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10')], null=True)),
                ('calculated_vote', models.FloatField(null=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='register.Application')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='invitation',
            fields=[
            ],
            options={
                'proxy': True,
            },
            bases=('register.application',),
        ),
        migrations.AlterUniqueTogether(
            name='vote',
            unique_together=set([('application', 'user')]),
        ),
    ]
