# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-06-26 04:12
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('edition', models.CharField(choices=[('F17', 'Fall 2017')], default='F17', max_length=7)),
                ('id', models.CharField(max_length=300, primary_key=True, serialize=False)),
                ('submission_date', models.DateTimeField()),
                ('status_update_date', models.DateTimeField(blank=True, null=True)),
                ('sendgrid_id', models.CharField(default='', max_length=300)),
                ('under_age', models.NullBooleanField()),
                ('first_timer', models.NullBooleanField()),
                ('description', models.CharField(max_length=500)),
                ('projects', models.CharField(max_length=500)),
                ('scholarship', models.NullBooleanField()),
                ('reimbursement_money', models.IntegerField(blank=True, null=True)),
                ('origin_city', models.CharField(max_length=300)),
                ('origin_country', models.CharField(max_length=300)),
                ('lennyface', models.CharField(default='-.-', max_length=300)),
                ('resume', models.URLField(blank=True, null=True)),
                ('team', models.NullBooleanField()),
                ('teammates', models.CharField(default='None', max_length=300)),
                ('authorized_mlh', models.NullBooleanField()),
                ('status', models.CharField(choices=[('S', 'Started'), ('CX', 'Completed'), ('R', 'Rejected'), ('I', 'Invited'), ('LR', 'Last reminder'), ('C', 'Confirmed'), ('X', 'Cancelled'), ('A', 'Attended'), ('E', 'Expired')], default='S', max_length=2)),
                ('invited_by', models.CharField(blank=True, max_length=300, null=True)),
            ],
            options={
                'permissions': (('invite', 'Can invite applications'), ('vote', 'Can review applications'), ('checkin', 'Can check-in applications'), ('reject', 'Can reject applications'), ('ranking', 'Can view voting ranking')),
            },
        ),
        migrations.CreateModel(
            name='Hacker',
            fields=[
                ('name', models.CharField(max_length=250)),
                ('lastname', models.CharField(max_length=250)),
                ('gender', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('NB', 'Non-binary')], max_length=20, null=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('graduation_year', models.IntegerField(choices=[(2016, b'2016'), (2017, b'2017'), (2018, b'2018'), (2019, b'2019')])),
                ('university', models.CharField(max_length=300)),
                ('degree', models.CharField(max_length=300)),
                ('github', models.URLField(blank=True, null=True)),
                ('devpost', models.URLField(blank=True, null=True)),
                ('linkedin', models.URLField(blank=True, null=True)),
                ('site', models.URLField(blank=True, null=True)),
                ('diet', models.CharField(choices=[('None', 'None'), ('Vegeterian', 'Vegeterian'), ('Gluten-free', 'Gluten free')], max_length=300)),
                ('tshirt_size', models.CharField(choices=[('XS', 'XS'), ('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL')], default='M', max_length=3)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tech', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10')], null=True)),
                ('personal', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10')], null=True)),
                ('calculated_vote', models.FloatField(null=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='register.Application')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='application',
            name='hacker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='register.Hacker'),
        ),
        migrations.AlterUniqueTogether(
            name='vote',
            unique_together=set([('application', 'user')]),
        ),
        migrations.AlterUniqueTogether(
            name='application',
            unique_together=set([('hacker', 'edition')]),
        ),
    ]
