# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-25 22:29
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    replaces = [('register', '0001_initial'), ('register', '0002_vote'), ('register', '0003_permission'), ('register', '0004_extra_applications'), ('register', '0005_fix_votes')]

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.TextField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('lastname', models.TextField()),
                ('email', models.TextField()),
                ('graduation', models.TextField()),
                ('university', models.TextField()),
                ('github', models.URLField()),
                ('devpost', models.URLField()),
                ('linkedin', models.URLField()),
                ('site', models.URLField()),
                ('first_timer', models.NullBooleanField()),
                ('description', models.TextField()),
                ('projects', models.TextField()),
                ('diet', models.TextField()),
                ('country', models.TextField()),
                ('schoolarship', models.NullBooleanField()),
                ('authorized_mlh', models.NullBooleanField()),
                ('status', models.CharField(choices=[('A', 'Accepted'), ('P', 'Pending'), ('R', 'Rejected'), ('I', 'Invited'), ('C', 'Confirmed'), ('X', 'Cancelled')], default='P', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote', models.IntegerField(choices=[(1, 'Positive'), (-1, 'Negative'), (0, 'Skipped')])),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='register.Application')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='vote',
            unique_together=set([('application', 'user')]),
        ),
        migrations.AlterModelOptions(
            name='application',
            options={'permissions': (('accept_application', 'Can accept applications'), ('invite_application', 'Can invite applications'), ('attended_application', 'Can mark as attended applications'), ('reject_application', 'Can reject applications'), ('force_status', 'Can force status application'))},
        ),
        migrations.AlterField(
            model_name='application',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('A', 'Accepted'), ('P', 'Pending'), ('R', 'Rejected'), ('I', 'Invited'), ('C', 'Confirmed'), ('X', 'Cancelled'), ('T', 'Attended')], default='P', max_length=1),
        ),
        migrations.RenameField(
            model_name='application',
            old_name='schoolarship',
            new_name='scholarship',
        ),
        migrations.AddField(
            model_name='application',
            name='degree',
            field=models.TextField(default='Computer Science'),
        ),
        migrations.AddField(
            model_name='application',
            name='lennyface',
            field=models.TextField(default='-.-'),
        ),
        migrations.AddField(
            model_name='application',
            name='submission_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='application',
            name='team',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='application',
            name='teammates',
            field=models.TextField(default='None'),
        ),
        migrations.AddField(
            model_name='application',
            name='tshirt_size',
            field=models.CharField(default='M', max_length=3),
        ),
        migrations.AddField(
            model_name='application',
            name='under_age',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='application',
            name='graduation',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('A', 'Accepted'), ('P', 'Pending'), ('R', 'Rejected'), ('I', 'Invited'), ('C', 'Confirmed'), ('X', 'Cancelled'), ('T', 'Attended')], default='P', max_length=2),
        ),
    ]
