# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-06-23 22:16
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.CharField(max_length=300, primary_key=True, serialize=False)),
                ('submission_date', models.DateTimeField()),
                ('status_update_date', models.DateTimeField(blank=True, null=True)),
                ('last_reminder', models.DateTimeField(blank=True, null=True)),
                ('sendgrid_id', models.CharField(default='', max_length=300)),
                ('under_age', models.NullBooleanField()),
                ('github', models.URLField()),
                ('devpost', models.URLField()),
                ('linkedin', models.URLField()),
                ('site', models.URLField()),
                ('resume', models.URLField()),
                ('first_timer', models.NullBooleanField()),
                ('description', models.CharField(max_length=300)),
                ('projects', models.CharField(max_length=300)),
                ('diet', models.CharField(max_length=300)),
                ('tshirt_size', models.CharField(default='M', max_length=3)),
                ('scholarship', models.NullBooleanField()),
                ('reimbursement_money', models.IntegerField(blank=True, null=True)),
                ('travel_origin', models.CharField(max_length=300)),
                ('lennyface', models.CharField(default='-.-', max_length=300)),
                ('team', models.NullBooleanField()),
                ('teammates', models.CharField(default='None', max_length=300)),
                ('authorized_mlh', models.NullBooleanField()),
                ('status', models.CharField(choices=[('S', 'Started'), ('P', 'Completed'), ('R', 'Rejected'), ('I', 'Invited'), ('C', 'Confirmed'), ('X', 'Cancelled'), ('T', 'Attended'), ('E', 'Expired')], default='S', max_length=2)),
                ('invited_by', models.CharField(max_length=300, null=True)),
            ],
            options={
                'permissions': (('invite', 'Can invite applications'), ('vote', 'Can review applications'), ('checkin', 'Can check-in applications'), ('reject', 'Can reject applications'), ('ranking', 'Can view voting ranking')),
            },
        ),
        migrations.CreateModel(
            name='Hacker',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('name', models.CharField(max_length=250)),
                ('lastname', models.CharField(max_length=250)),
                ('country', models.CharField(max_length=250)),
                ('gender', models.CharField(max_length=20, null=True)),
                ('graduationYear', models.IntegerField()),
                ('university', models.CharField(max_length=300)),
                ('degree', models.CharField(default='Computer Science', max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tech', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10')], null=True)),
                ('personal', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10')], null=True)),
                ('calculated_vote', models.FloatField(null=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='register.Application')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='application',
            name='hacker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='register.Hacker'),
        ),
        migrations.AlterUniqueTogether(
            name='vote',
            unique_together=set([('application', 'user')]),
        ),
    ]
