# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-06-26 03:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hacker',
            name='resume',
        ),
        migrations.AddField(
            model_name='application',
            name='resume',
            field=models.URLField(blank=True, null=True),
        ),
    ]
