# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-06-26 03:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='invited_by',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='hacker',
            name='devpost',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hacker',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('NB', 'Non-binary')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='hacker',
            name='github',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hacker',
            name='linkedin',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hacker',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to=b''),
        ),
        migrations.AlterField(
            model_name='hacker',
            name='site',
            field=models.URLField(blank=True, null=True),
        ),
    ]
