# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-25 13:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0002_vote'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='application',
            options={'permissions': (('accept_application', 'Can accept applications'), ('invite_application', 'Can invite applications'), ('attended_application', 'Can mark as attended applications'), ('reject_application', 'Can reject applications'), ('force_status', 'Can force status application'))},
        ),
        migrations.AlterField(
            model_name='application',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('A', 'Accepted'), ('P', 'Pending'), ('R', 'Rejected'), ('I', 'Invited'), ('C', 'Confirmed'), ('X', 'Cancelled'), ('T', 'Attended')], default='P', max_length=1),
        ),
    ]
