# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-06-26 17:15
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0002_fixstates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='invited_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
