# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-25 16:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0003_permission'),
    ]

    operations = [
        migrations.RenameField(
            model_name='application',
            old_name='schoolarship',
            new_name='scholarship',
        ),
        migrations.AddField(
            model_name='application',
            name='degree',
            field=models.TextField(default='Computer Science'),
        ),
        migrations.AddField(
            model_name='application',
            name='lennyface',
            field=models.TextField(default='-.-'),
        ),
        migrations.AddField(
            model_name='application',
            name='submission_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='application',
            name='team',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='application',
            name='teammates',
            field=models.TextField(default='None'),
        ),
        migrations.AddField(
            model_name='application',
            name='tshirt_size',
            field=models.CharField(default='M', max_length=3),
        ),
        migrations.AddField(
            model_name='application',
            name='under_age',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='application',
            name='graduation',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('A', 'Accepted'), ('P', 'Pending'), ('R', 'Rejected'), ('I', 'Invited'), ('C', 'Confirmed'), ('X', 'Cancelled'), ('T', 'Attended')], default='P', max_length=2),
        ),
    ]
