# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-25 17:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0003_votes-refactor'),
    ]

    operations = [
        migrations.CreateModel(
            name='invitation',
            fields=[
            ],
            options={
                'proxy': True,
            },
            bases=('register.application',),
        ),
        migrations.AddField(
            model_name='application',
            name='invitation_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
