# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-25 22:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0004_extra_applications'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='vote',
            field=models.IntegerField(choices=[(1, 'Positive'), (-1, 'Negative'), (0, 'Skipped')]),
        ),
    ]
