# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-30 15:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0004_auto_20170125_1726'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='reimbursement_money',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
