# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-04 15:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0005_reimbursements'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='last_reminder',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('A', 'Accepted'), ('P', 'Pending'), ('R', 'Rejected'), ('I', 'Invited'), ('C', 'Confirmed'), ('X', 'Cancelled'), ('T', 'Attended'), ('E', 'Expired')], default='P', max_length=2),
        ),
    ]
