# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-06-28 23:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0006_sendgrid_null'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='application',
            options={'permissions': (('invite', 'Can invite applications'), ('vote', 'Can review applications'), ('reject', 'Can reject applications'), ('ranking', 'Can view voting ranking'))},
        ),
    ]
