# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-06-29 21:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0007_checkin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='reimbursement_money',
        ),
    ]
