# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-08-03 15:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0009_vegan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hacker',
            name='diet',
            field=models.CharField(choices=[('None', 'No requirements'), ('Vegeterian', 'Vegeterian'), ('Vegan', 'Vegan'), ('No pork', 'No pork'), ('Gluten-free', 'Gluten-free'), ('Others', 'Others')], max_length=300),
        ),
        migrations.AlterField(
            model_name='hacker',
            name='graduation_year',
            field=models.IntegerField(choices=[(2016, '2016'), (2017, '2017'), (2018, '2018'), (2019, '2019'), (2020, '2020'), (2021, '2021'), (2022, '2022'), (2023, '2023')]),
        ),
    ]
