# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-08-03 18:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0010_more_years'),
    ]

    operations = [
        migrations.AddField(
            model_name='hacker',
            name='other_diet',
            field=models.CharField(blank=True, max_length=600, null=True),
        ),
    ]
