# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-08-08 12:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0011_add_date_comment'),
        ('register', '0011_otherstext'),
    ]

    operations = [
    ]
