# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-09-05 15:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0012_merge_20170808_1230'),
    ]

    operations = [
        migrations.AddField(
            model_name='hacker',
            name='reminders_sent',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='hacker',
            name='graduation_year',
            field=models.IntegerField(choices=[(2016, b'2016'), (2017, b'2017'), (2018, b'2018'), (2019, b'2019'), (2020, b'2020'), (2021, b'2021'), (2022, b'2022'), (2023, b'2023')]),
        ),
    ]
