# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-06-28 23:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkin', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='checkin',
            options={'permissions': (('checkin', 'Can checkin applications'),)},
        ),
    ]
