# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2019-02-02 16:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkin',
            name='check_type',
            field=models.CharField(choices=[('arrived', 'Hacker arrived'), ('sat_lunch', 'Saturday lunch'), ('sat_dinner', 'Saturday dinner'), ('sun_lunch', 'Sunday lunch')], default='arrived', max_length=10),
            preserve_default=False,
        ),
    ]
