# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-09-29 21:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkin',
            name='qr_identifier',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
