# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-05-07 09:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0026_auto_20200428_0253'),
        ('checkin', '0002_to_new_applications_20200402_1036'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkin',
            name='hacker',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='applications.HackerApplication'),
        ),
        migrations.AddField(
            model_name='checkin',
            name='mentor',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='applications.MentorApplication'),
        ),
        migrations.AddField(
            model_name='checkin',
            name='sponsor',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='applications.SponsorApplication'),
        ),
        migrations.AddField(
            model_name='checkin',
            name='volunteer',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='applications.VolunteerApplication'),
        ),
        migrations.RemoveField(
            model_name='checkin',
            name='application',
        ),
    ]
