# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-10-12 15:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkin', '0002_checkin'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkin',
            name='signed_lopd',
            field=models.BooleanField(default=False),
        ),
    ]
