# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-10-10 18:13
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('checkin', '0002_checkin_qr_identifier'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkin',
            name='application',
        ),
        migrations.AddField(
            model_name='checkin',
            name='application_user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='application_user', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='checkin',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL),
        ),
    ]
