# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2019-02-02 18:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('checkin', '0002_checkin_check_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkin',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='applications.Application'),
        ),
        migrations.AlterField(
            model_name='checkin',
            name='check_type',
            field=models.CharField(choices=[('arrived', 'Hacker arrival'), ('sat_lunch', 'Saturday lunch'), ('sat_dinner', 'Saturday dinner'), ('sun_lunch', 'Sunday lunch')], max_length=10),
        ),
    ]
