# Generated by Django 3.2.7 on 2023-05-07 18:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0041_auto_20230303_1741'),
        ('checkin', '0007_alter_checkin_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkin',
            name='hacker',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='applications.hackerapplication'),
        ),
        migrations.AlterField(
            model_name='checkin',
            name='mentor',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='applications.mentorapplication'),
        ),
        migrations.AlterField(
            model_name='checkin',
            name='sponsor',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='applications.sponsorapplication'),
        ),
        migrations.AlterField(
            model_name='checkin',
            name='volunteer',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='applications.volunteerapplication'),
        ),
    ]
