# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-10-24 05:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.CharField(max_length=255, unique=True, verbose_name='email')),
                ('nickname', models.CharField(max_length=255, verbose_name='Nickname')),
                ('email_verified', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_volunteer', models.BooleanField(default=False)),
                ('is_organizer', models.BooleanField(default=False)),
                ('is_director', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
