# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-11-01 23:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='nickname',
            field=models.CharField(max_length=255, verbose_name='Preferred name'),
        ),
    ]
