# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-09-17 19:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_makeemailfield'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_hardware_admin',
            field=models.BooleanField(default=False),
        ),
    ]
