# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-12-05 18:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_user_is_hardware_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='mlh_id',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
