# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-09-25 08:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_user_is_hardware_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='qr_identifier',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
