# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2019-02-03 18:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_user_is_hardware_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_external',
            field=models.BooleanField(default=False),
        ),
    ]
