# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2019-07-25 11:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_user_mlh_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='can_review_dubious',
            field=models.BooleanField(default=False),
        ),
    ]
