# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-07-08 10:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_user_mlh_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_hx',
            field=models.BooleanField(default=False),
        ),
    ]
