# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-03-16 16:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_user_can_review_dubious'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='can_review_blacklist',
            field=models.BooleanField(default=False),
        ),
    ]
