# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2019-08-08 16:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_user_is_hx'),
        ('user', '0008_user_can_review_dubious'),
    ]

    operations = [
    ]
