# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-02-06 08:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_user_can_review_dubious'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_organizer',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_volunteer',
        ),
        migrations.AddField(
            model_name='user',
            name='type',
            field=models.CharField(choices=[('O', 'Organizer'), ('V', 'Volunteer'), ('H', 'Hacker'), ('M', 'Mentor'), ('S', 'Sponsor')], default='H', max_length=2),
        ),
    ]
