# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2019-08-08 23:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_merge_20190808_1809'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_hx'
        ),
    ]
