# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-03-28 14:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_blacklistuser'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blacklistuser',
            old_name='justification',
            new_name='motive_of_ban',
        ),
        migrations.AddField(
            model_name='blacklistuser',
            name='date_of_ban',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
