# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-05-19 18:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_auto_20200507_0751'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='max_applications',
            field=models.IntegerField(default=1),
        ),
    ]
