# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-10-10 20:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_auto_20191010_1815'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='diet',
            field=models.CharField(blank=True, choices=[('None', 'No requirements'), ('Vegeterian', 'Vegeterian'), ('Vegan', 'Vegan'), ('No pork', 'No pork'), ('Gluten-free', 'Gluten-free'), ('Others', 'Others')], max_length=300, null=True),
        ),
    ]
