# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-07-09 09:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0015_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='diet',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_mentor',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_sponsor',
        ),
    ]
