# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-03-28 14:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0016_auto_20200709_1127'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_subscribed',
            field=models.BooleanField(default=False),
        ),
    ]
