# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2021-10-02 20:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0017_user_email_subscribed'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=30)),
                ('latestRequest', models.DateTimeField()),
                ('login_tries', models.IntegerField(default=1)),
            ],
        ),
    ]
