# Generated by Django 3.2.7 on 2023-04-03 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0018_loginrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='mlh_subscribed',
            field=models.BooleanField(default=False),
        ),
    ]
